service: lookschool-backend

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 512
  timeout: 15
  region: us-east-1
  apiName: lookscholl-api

functions:
  api:
    name: lookschool-backend
    handler: lambda.handler
    events:
      - httpApi:
          path: /
          method: GET
      - httpApi:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline
