const STATUS_INACTIVE = 0;
const STATUS_ACTIVE = 1;
const STATUS_PENDING = 2;
const STATUS_FAILED = 3;
const STATUS_BLOCKED = 4;

const COUNTRY_BRAZIL = 0;
const COUNTRY_USA = 1;
const COUNTRY_SPAIN = 2;

const LANGUAGE_PORTUGUESE = 0;
const LANGUAGE_ENGLISH = 1;
const LANGUAGE_SPANISH = 2;

module.exports = {
  STATUS_INACTIVE,
  STATUS_ACTIVE,
  STATUS_PENDING,
  STATUS_FAILED,
  STATUS_BLOCKED,
  COUNTRY_BRAZIL,
  COUNTRY_USA,
  COUNTRY_SPAIN,
  LANGUAGE_PORTUGUESE,
  LANGUAGE_ENGLISH,
  LANGUAGE_SPANISH,
};
